add Joint_states_subscriber to apps
micro-ROS/freertos_apps pull request #69
Opened 2021-04-21 11:20 UTC by Needrom

add joint_states topic for test

2021-04-21 11:30 UTC, pablogs9 requested changes

2021-04-21 11:30 UTC, pablogs9 commented on apps/joint_states_subscriber/app.c
> +char test_array[ARRAY_LEN];
Delete

2021-04-21 11:30 UTC, pablogs9 commented on apps/joint_states_subscriber/app.c
> +  	memset(test_array,'z',ARRAY_LEN);
Delete

2021-04-22 02:50 UTC, closed without merging

2021-04-22 02:50 UTC, Needrom commented
OK

2021-04-22 05:41 UTC, pablogs9 commented
For the next time, if you push commits to the same branch the PR is updated. You don't need to close and open a new one.